[package]
name = "rust-camera"
version = "0.1.0"
authors = ["Jens Streck <jens.streck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v4l = { version = "0.12.0", features = ["v4l2-sys"] }